import type { Metadata } from "next";
import { ScrollText } from "lucide-react";
import { LegalPage, type LegalSection } from "@/components/legal/LegalPage";
import { SUPPORT_EMAIL } from "@/lib/seo";

export const metadata: Metadata = {
  title: "Terms of Service — Heightt",
  description: "The terms that apply when students and organisations use Heightt.",
  alternates: { canonical: "/terms" },
};

const sections: LegalSection[] = [
  { id: "agreement", title: "Agreement to these terms", content: <p>These terms govern your access to and use of Heightt’s websites, applications, payment and receipt features, and related services. By creating an account, using guest checkout, or otherwise using Heightt, you agree to these terms and our Privacy Policy. If you use Heightt for an organisation, you confirm that you are authorised to act for it.</p> },
  { id: "eligibility", title: "Eligibility and accounts", content: <><p>You must have legal capacity to agree to these terms. If local law requires permission from a parent, guardian, institution, or another representative, you must obtain it before using Heightt.</p><p>Provide accurate information, keep it current, protect your password and verification codes, and promptly report suspected unauthorised use. You are responsible for activity performed through your account unless applicable law provides otherwise. Usernames are case-insensitive and must follow our displayed format rules.</p></> },
  { id: "service", title: "What Heightt provides", content: <p>Heightt provides software for student organisations and their members to manage memberships, create and assign dues, initiate payments, track payment status, communicate, and generate receipts and financial records. Features may differ by institution, organisation, role, location, or rollout stage. An organisation controls the dues it creates, their audience, amount, timing, and purpose.</p> },
  { id: "organisations", title: "Organisations and administrators", content: <><p>Organisation administrators must act within their authority and use member information only for legitimate organisation purposes. They are responsible for the accuracy and lawfulness of dues, membership decisions, announcements, roles, and records they create.</p><p>Administrators must not misrepresent an organisation, assign unauthorised charges, misuse student data, conceal material payment information, or grant permissions to people who should not have them. Heightt may review, restrict, or suspend organisation access where needed to protect users or the platform.</p></> },
  { id: "dues-payments", title: "Dues and payments", content: <><p>Before paying, review the due, organisation, amount, audience, and session shown. Heightt sends payment instructions to a third-party provider and records the status returned through checkout and reconciliation services. Your bank or payment provider may apply separate processing charges or terms.</p><p>A payment is complete only when Heightt receives and records successful confirmation. A pending screen, debit alert, or checkout redirect alone may not be final confirmation. Do not start repeated payments while an earlier attempt is still pending; use the status and support tools provided.</p></> },
  { id: "guest-payments", title: "Guest payments and claims", content: <p>You may be able to pay without an account by providing accurate identity and academic information. Keep access links and codes secure. To claim a guest payment later, use an account with the same verified email and complete the claim process. Heightt may refuse a claim where the information cannot be verified or where doing so could expose another person’s records.</p> },
  { id: "receipts-refunds", title: "Receipts, disputes, and refunds", content: <><p>A Heightt receipt records a payment confirmed through the platform. It does not independently verify how an organisation uses collected funds or replace any additional clearance process imposed by an institution.</p><p>Refund eligibility depends on the circumstances, the collecting organisation’s rules, applicable law, and payment-provider requirements. Contact the organisation or Heightt promptly with the transaction reference if a charge is incorrect, duplicated, or disputed. Nothing in these terms limits consumer rights that cannot lawfully be excluded.</p></> },
  { id: "acceptable-use", title: "Acceptable use", content: <><p>You may not use Heightt to:</p><ul><li>break the law, facilitate fraud, impersonate another person, or provide information you know is false;</li><li>access accounts, records, organisations, or systems without permission;</li><li>interfere with security, probe vulnerabilities, introduce harmful code, scrape the service at scale, or overload infrastructure;</li><li>harass users, publish unlawful content, or misuse personal and financial information; or</li><li>copy, resell, reverse engineer, or exploit the service except where the law expressly permits it.</li></ul></> },
  { id: "third-parties", title: "Third-party services", content: <p>Heightt relies on third parties for services such as payment processing, email delivery, hosting, and file storage. Their services may be governed by separate terms and may occasionally be unavailable. Heightt is not responsible for a third party’s independent acts, but we will take reasonable steps to help investigate platform-related payment and service issues.</p> },
  { id: "intellectual-property", title: "Intellectual property", content: <p>Heightt and its licensors own the platform, branding, software, and original content. We grant you a limited, revocable, non-exclusive, non-transferable right to use the service for its intended purpose. You retain ownership of content you lawfully submit and grant Heightt permission to host, process, display, and transmit it as needed to provide and protect the service.</p> },
  { id: "availability", title: "Availability and changes", content: <p>We work to keep Heightt reliable and accurate, but the service may be interrupted for maintenance, security, provider outages, or circumstances outside our control. We may add, change, or discontinue features and will provide reasonable notice where a change materially affects active users or paid services.</p> },
  { id: "liability", title: "Disclaimers and liability", content: <><p>To the extent permitted by law, Heightt is provided on an “as available” basis. We do not guarantee uninterrupted operation or that information entered by organisations is complete or accurate.</p><p>Heightt is not responsible for an organisation’s internal decisions or use of funds. Our liability will not be excluded where doing so would be unlawful, including liability that cannot be limited under applicable consumer law. Otherwise, we are not liable for indirect or consequential loss arising from use of the service.</p></> },
  { id: "suspension", title: "Suspension and termination", content: <p>You may stop using Heightt at any time. We may restrict or terminate access where you breach these terms, create security or legal risk, misuse payment features, or where suspension is required by an authority or service provider. Provisions concerning payments, records, ownership, disputes, and liability continue where their nature requires it.</p> },
  { id: "law-disputes", title: "Governing law and disputes", content: <p>These terms are governed by the laws of the Federal Republic of Nigeria. Please contact us first so we can try to resolve a dispute informally. If it cannot be resolved, either party may use a court or other dispute-resolution process with jurisdiction under applicable law. Any mandatory consumer right or forum remains available to you.</p> },
  { id: "changes-contact", title: "Changes and contact", content: <p>We may revise these terms to reflect changes to Heightt, providers, or the law. The revised terms will be posted here with a new effective date, and material changes may receive additional notice. Continuing to use Heightt after revised terms take effect means you accept them. Questions can be sent to <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</p> },
];

export default function TermsPage() {
  return <LegalPage eyebrow="Rules for using Heightt" title="Terms of Service" description="The practical terms that keep payments, organisations, and student records clear and dependable." effectiveDate="7 September 2026" icon={ScrollText} highlights={["Organisations remain responsible for the dues and information they publish.", "A payment is complete only after successful confirmation is recorded.", "Refunds depend on the circumstances, organisation rules, provider requirements, and applicable law.", "Accounts, administrator permissions, and verification codes must be used responsibly."]} sections={sections} companion={{ label: "Privacy Policy", href: "/privacy" }} />;
}
